server:
  port: 8084
  servlet:
    context-path: /score

spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/market?useUnicode=true&characterEncoding=utf8&useSSL=false"
    username: root
    password: 123456


mybatis:
  configuration:
    map-underscore-to-camel-case: true
