server:
  port: 8082
  servlet:
    context-path: /pay

mybatis:
  configuration:
    map-underscore-to-camel-case: true
spring:
  application:
    name: pay


simpletx:
  server:
    host: 127.0.0.1
    port: 10290
    password: 123
    maxActive: 10