server:
  port: 8083
  servlet:
    context-path: /balance

spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/market?useUnicode=true&characterEncoding=utf8&useSSL=false"
    username: root
    password: 123456
  application:
    name: sample-http-balance


mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.xiaojiezhu: trace


simpletx:
  server:
    host: 127.0.0.1
    port: 10290
    password: hello
    maxActive: 10