server:
  port: 8080
  servlet:
    context-path: /order

mybatis:
  configuration:
    map-underscore-to-camel-case: true

spring:
  application:
    name: order


simpletx:
  server:
    host: 127.0.0.1
    port: 10290
    password: 123
    maxActive: 5